In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

In [4]:
arr= [1,2,3,4,5]
np_arr = np.array(arr)
print(type(arr))
print(type(np_arr))

<class 'list'>
<class 'numpy.ndarray'>


In [7]:
arr = np.arange(15)
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [8]:
arr = np.arange(15).reshape(3,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- python의 range함수와 비슷하게 사용 가능

- indexing

In [11]:
arr = np.arange(25).reshape(5,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [9]:
print(arr[1][2])

7


In [12]:
print(arr[1:3, :2]) # 1,2 번 행 / 0,1 번 열

[[ 5  6]
 [10 11]]


원본배열을 수정하지 않으려면 np.copy() 함수를 활용

In [13]:
arr2 = arr
arr2[0][0] = 10
print(arr)
print(arr2)

[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[10  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [14]:
arr = np.arange(15).reshape(3,5)
arr2 = arr.copy()
arr2[0][0] = 15
print(arr)
print(arr2)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[15  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
